version: "3.3"
services:
  bank-db:
    image: postgres
    container_name: bank_db
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
    restart: on-failure
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  server:
    container_name: bank
    build: .
    depends_on:
      - bank-db
    networks:
      - default
    ports:
      - "${APP_PORT}:${APP_PORT}"
  
volumes:
  postgres-data:
